version: '3.8'

services:
  app:
    build: .
    container_name: dashboard-ai-app
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./app
        target: /app/app

